require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BlockListServersController do

  # This should return the minimal set of attributes required to create a valid
  # BlockListServer. As you add validations to BlockListServer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BlockListServersController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all block_list_servers as @block_list_servers" do
      block_list_server = BlockListServer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:block_list_servers).should eq([block_list_server])
    end
  end

  describe "GET show" do
    it "assigns the requested block_list_server as @block_list_server" do
      block_list_server = BlockListServer.create! valid_attributes
      get :show, {:id => block_list_server.to_param}, valid_session
      assigns(:block_list_server).should eq(block_list_server)
    end
  end

  describe "GET new" do
    it "assigns a new block_list_server as @block_list_server" do
      get :new, {}, valid_session
      assigns(:block_list_server).should be_a_new(BlockListServer)
    end
  end

  describe "GET edit" do
    it "assigns the requested block_list_server as @block_list_server" do
      block_list_server = BlockListServer.create! valid_attributes
      get :edit, {:id => block_list_server.to_param}, valid_session
      assigns(:block_list_server).should eq(block_list_server)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new BlockListServer" do
        expect {
          post :create, {:block_list_server => valid_attributes}, valid_session
        }.to change(BlockListServer, :count).by(1)
      end

      it "assigns a newly created block_list_server as @block_list_server" do
        post :create, {:block_list_server => valid_attributes}, valid_session
        assigns(:block_list_server).should be_a(BlockListServer)
        assigns(:block_list_server).should be_persisted
      end

      it "redirects to the created block_list_server" do
        post :create, {:block_list_server => valid_attributes}, valid_session
        response.should redirect_to(BlockListServer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved block_list_server as @block_list_server" do
        # Trigger the behavior that occurs when invalid params are submitted
        BlockListServer.any_instance.stub(:save).and_return(false)
        post :create, {:block_list_server => { "name" => "invalid value" }}, valid_session
        assigns(:block_list_server).should be_a_new(BlockListServer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        BlockListServer.any_instance.stub(:save).and_return(false)
        post :create, {:block_list_server => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested block_list_server" do
        block_list_server = BlockListServer.create! valid_attributes
        # Assuming there are no other block_list_servers in the database, this
        # specifies that the BlockListServer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        BlockListServer.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => block_list_server.to_param, :block_list_server => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested block_list_server as @block_list_server" do
        block_list_server = BlockListServer.create! valid_attributes
        put :update, {:id => block_list_server.to_param, :block_list_server => valid_attributes}, valid_session
        assigns(:block_list_server).should eq(block_list_server)
      end

      it "redirects to the block_list_server" do
        block_list_server = BlockListServer.create! valid_attributes
        put :update, {:id => block_list_server.to_param, :block_list_server => valid_attributes}, valid_session
        response.should redirect_to(block_list_server)
      end
    end

    describe "with invalid params" do
      it "assigns the block_list_server as @block_list_server" do
        block_list_server = BlockListServer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BlockListServer.any_instance.stub(:save).and_return(false)
        put :update, {:id => block_list_server.to_param, :block_list_server => { "name" => "invalid value" }}, valid_session
        assigns(:block_list_server).should eq(block_list_server)
      end

      it "re-renders the 'edit' template" do
        block_list_server = BlockListServer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        BlockListServer.any_instance.stub(:save).and_return(false)
        put :update, {:id => block_list_server.to_param, :block_list_server => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested block_list_server" do
      block_list_server = BlockListServer.create! valid_attributes
      expect {
        delete :destroy, {:id => block_list_server.to_param}, valid_session
      }.to change(BlockListServer, :count).by(-1)
    end

    it "redirects to the block_list_servers list" do
      block_list_server = BlockListServer.create! valid_attributes
      delete :destroy, {:id => block_list_server.to_param}, valid_session
      response.should redirect_to(block_list_servers_url)
    end
  end

end
